$:.unshift(File.dirname(__FILE__) + '/../../lib')
require 'cucumber/rake/task'

Cucumber::Rake::Task.new do |t|
  t.cucumber_opts = %w{--format pretty}
end

desc "run cucumber with cucumber-1.9"
task "cucumber-1.9" do
  cd "features/"
  sh "cucumber-1.9 *.feature"
end

desc "run rspec"
task "spec" do
  sh "spec spec/*.rb"
end

desc "run rspec with spec-1.9"
task "spec-1.9" do
  sh "spec-1.9 spec/*.rb"
end
